update up to 0.27.0
nspcc-dev/ansible-neofs-storage pull request #19
Opened 2021-12-09 19:09 UTC by anatoly-bogatyrev

- update up to 0.27.0

2021-12-10 06:55 UTC, 532910 requested changes
Update units in bytes to suffixes please.

2021-12-10 08:06 UTC, anatoly-bogatyrev commented
> 

has been fixed

2021-12-10 08:52 UTC, 532910 commented
Though neofs handles space before suffix, I'd advise to avoid it, as it could be treated as a different argument.

2021-12-11 11:45 UTC, 532910 approved these changes

2021-12-11 17:08 UTC, merged